# Generated by Django 5.2.4 on 2025-09-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='baptism_date',
            field=models.DateField(blank=True, help_text='Data do batismo', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF do membro (formato: XXX.XXX.XXX-XX)', max_length=14, null=True, unique=True),
        ),
    ]
