# Generated by Django 5.2.4 on 2025-09-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_baptism_date_customuser_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
