from django.urls import path
from worship.views import (
    WorshipHomeView,
    SongSearchView,
    SongAddView,
    SongDetailView,
    SongCreateView,
    SongListView,
    add_song_file,
    SongFileListView,
    WorshipCatalogSettingsView,
    WorshipServiceListView,
    WorshipServiceCreateView,
    WorshipServiceDetailView,
    WorshipServiceUpdateView,
    WorshipServiceDeleteView,
    WorshipServiceDuplicateView,
    WorshipServiceFontScaleView,
    WorshipServiceGenerateProgramView,
    WorshipServiceSongCreateView,
    WorshipServiceSongDeleteView,
    WorshipServiceSongResolveView,
    WorshipServiceSongSyncFromProgramView,
    WorshipServiceImportView,
    WorshipServicePrintView,
    WorshipServicePdfView,
)
from worship.views.search import (
    ComposerListView,
    ThemeListView,
    HymnalListView,
)

app_name = "worship"

urlpatterns = [
    path("", WorshipHomeView.as_view(), name="home"),
    path("services/", WorshipServiceListView.as_view(), name="service-list"),
    path("services/new/", WorshipServiceCreateView.as_view(), name="service-create"),
    path("services/import/", WorshipServiceImportView.as_view(), name="service-import"),
    path("services/<int:pk>/", WorshipServiceDetailView.as_view(), name="service-detail"),
    path("services/<int:pk>/edit/", WorshipServiceUpdateView.as_view(), name="service-edit"),
    path("services/<int:pk>/delete/", WorshipServiceDeleteView.as_view(), name="service-delete"),
    path("services/<int:pk>/duplicate/", WorshipServiceDuplicateView.as_view(), name="service-duplicate"),
    path("services/<int:pk>/font-scale/", WorshipServiceFontScaleView.as_view(), name="service-font-scale"),
    path("services/<int:pk>/generate/", WorshipServiceGenerateProgramView.as_view(), name="service-generate"),
    path("services/<int:pk>/songs/sync/", WorshipServiceSongSyncFromProgramView.as_view(), name="service-song-sync"),
    path("services/<int:pk>/songs/add/", WorshipServiceSongCreateView.as_view(), name="service-song-add"),
    path("services/<int:pk>/songs/<int:song_id>/delete/", WorshipServiceSongDeleteView.as_view(), name="service-song-delete"),
    path("services/<int:pk>/songs/<int:song_id>/resolve/", WorshipServiceSongResolveView.as_view(), name="service-song-resolve"),
    path("services/<int:pk>/print/", WorshipServicePrintView.as_view(), name="service-print"),
    path("services/<int:pk>/pdf/", WorshipServicePdfView.as_view(), name="service-pdf"),
    path("songs/search/", SongSearchView.as_view(), name="song-search"),
    path("songs/", SongListView.as_view(), name="song-list"),
    path("songs/new/", SongCreateView.as_view(), name="song-create"),
    path("catalog-settings/", WorshipCatalogSettingsView.as_view(), name="catalog-settings"),
    path("song-add/", SongAddView.as_view(), name="song-add"),
    path('composers/', ComposerListView.as_view(), name='composer-list'),
    path('themes/', ThemeListView.as_view(), name='song-themes'),
    path('hymnals/', HymnalListView.as_view(), name='hymnal-list'),
    path('song/<int:pk>/', SongDetailView.as_view(), name='song-detail'),
    path('song-files/add/', add_song_file, name='add-song-file'),
    path('song-files/', SongFileListView.as_view(), name='get-song-files'),
]
