# Generated by Django 4.2.5 on 2024-05-13 19:41

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingAgendaModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateField(auto_now_add=True, verbose_name="Data de Criação"),
                ),
                (
                    "modified",
                    models.DateField(
                        auto_now_add=True, verbose_name="Data de Atualização"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                ("agenda_title", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Assunto de Reunião",
                "verbose_name_plural": "Assuntos de Reunião",
            },
        ),
        migrations.CreateModel(
            name="MinuteExcerptsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateField(auto_now_add=True, verbose_name="Data de Criação"),
                ),
                (
                    "modified",
                    models.DateField(
                        auto_now_add=True, verbose_name="Data de Atualização"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                ("title", models.CharField(max_length=100)),
                ("excerpt", models.CharField(max_length=1000)),
                ("times_used", models.IntegerField(default=1)),
            ],
            options={
                "verbose_name": "Trecho de Atas",
                "verbose_name_plural": "Trechos de Atas",
            },
        ),
        migrations.CreateModel(
            name="MinuteTemplateModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateField(auto_now_add=True, verbose_name="Data de Criação"),
                ),
                (
                    "modified",
                    models.DateField(
                        auto_now_add=True, verbose_name="Data de Atualização"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                ("title", models.CharField(max_length=255)),
                ("body", ckeditor.fields.RichTextField(blank=True, null=True)),
                (
                    "agenda",
                    models.ManyToManyField(
                        blank=True, to="secretarial.meetingagendamodel"
                    ),
                ),
            ],
            options={
                "verbose_name": "Modelo de Ata",
                "verbose_name_plural": "Modelos de Ata",
            },
        ),
        migrations.CreateModel(
            name="MinuteProjectModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateField(auto_now_add=True, verbose_name="Data de Criação"),
                ),
                (
                    "modified",
                    models.DateField(
                        auto_now_add=True, verbose_name="Data de Atualização"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                ("meeting_date", models.DateField()),
                ("number_of_attendees", models.CharField(max_length=3)),
                ("previous_minute_reading", models.BooleanField(default=True)),
                ("previous_finance_report_reading", models.BooleanField(default=True)),
                (
                    "last_months_balance",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("revenue", models.DecimalField(decimal_places=2, max_digits=8)),
                ("expenses", models.DecimalField(decimal_places=2, max_digits=8)),
                ("body", ckeditor.fields.RichTextField(blank=True, null=True)),
                (
                    "finance_report_acceptance_proposal",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fr_acceptor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "finance_report_acceptance_proposal_support",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fr_supporter",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "meeting_agenda",
                    models.ManyToManyField(to="secretarial.meetingagendamodel"),
                ),
                (
                    "minute_reading_acceptance_proposal",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mr_acceptor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "minute_reading_acceptance_proposal_support",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mr_supporter",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "president",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meet_president",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "secretary",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meet_secretary",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "treasurer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meet_treasurer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Projeto de Ata",
                "verbose_name_plural": "Projeto de Ata",
            },
        ),
        migrations.CreateModel(
            name="MeetingMinuteModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateField(auto_now_add=True, verbose_name="Data de Criação"),
                ),
                (
                    "modified",
                    models.DateField(
                        auto_now_add=True, verbose_name="Data de Atualização"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                ("meeting_date", models.DateField()),
                ("number_of_attendees", models.IntegerField()),
                ("body", ckeditor.fields.RichTextField(blank=True, null=True)),
                (
                    "agenda",
                    models.ManyToManyField(
                        blank=True, to="secretarial.meetingagendamodel"
                    ),
                ),
                (
                    "president",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="president",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "secretary",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="secretary",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ata",
                "verbose_name_plural": "Atas",
            },
        ),
    ]
