# Generated by Django 4.2.5 on 2025-05-16 19:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("secretarial", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetingminutemodel",
            name="agenda",
            field=models.ManyToManyField(
                blank=True, null=True, to="secretarial.meetingagendamodel"
            ),
        ),
        migrations.AlterField(
            model_name="meetingminutemodel",
            name="meeting_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="meetingminutemodel",
            name="number_of_attendees",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="meetingminutemodel",
            name="president",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="president",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="meetingminutemodel",
            name="secretary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="secretary",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
