# Generated by Django 4.2.5 on 2025-05-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("secretarial", "0002_alter_meetingminutemodel_agenda_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetingminutemodel",
            name="agenda",
            field=models.ManyToManyField(
                blank=True, to="secretarial.meetingagendamodel"
            ),
        ),
    ]
