# Generated by Django 5.2.4 on 2025-09-13 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretarial', '0003_alter_meetingminutemodel_agenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinuteFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modified', models.DateField(auto_now_add=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('file', models.FileField(upload_to='minutes/attachments/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('minute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='secretarial.meetingminutemodel')),
            ],
            options={
                'verbose_name': 'Arquivo da Ata',
                'verbose_name_plural': 'Arquivos da Ata',
            },
        ),
    ]
