# Generated by Django 5.2.4 on 2025-09-14 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretarial', '0004_minutefilemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minuteprojectmodel',
            name='expenses',
        ),
        migrations.RemoveField(
            model_name='minuteprojectmodel',
            name='finance_report_acceptance_proposal',
        ),
        migrations.RemoveField(
            model_name='minuteprojectmodel',
            name='finance_report_acceptance_proposal_support',
        ),
        migrations.RemoveField(
            model_name='minuteprojectmodel',
            name='last_months_balance',
        ),
        migrations.RemoveField(
            model_name='minuteprojectmodel',
            name='meeting_agenda',
        ),
        migrations.RemoveField(
            model_name='minuteprojectmodel',
            name='minute_reading_acceptance_proposal',
        ),
        migrations.RemoveField(
            model_name='minuteprojectmodel',
            name='minute_reading_acceptance_proposal_support',
        ),
        migrations.RemoveField(
            model_name='minuteprojectmodel',
            name='previous_finance_report_reading',
        ),
        migrations.RemoveField(
            model_name='minuteprojectmodel',
            name='previous_minute_reading',
        ),
        migrations.RemoveField(
            model_name='minuteprojectmodel',
            name='revenue',
        ),
        migrations.RemoveField(
            model_name='minuteprojectmodel',
            name='treasurer',
        ),
    ]
