# Generated by Django 5.2.4 on 2026-01-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretarial', '0005_remove_minuteprojectmodel_expenses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minuteexcerptsmodel',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
    ]
