# Generated by Django 5.2.4 on 2026-04-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretarial', '0006_alter_minuteexcerptsmodel_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingminutemodel',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='minuteprojectmodel',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='minutetemplatemodel',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
