# Generated by Django 4.2.5 on 2024-10-26 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Composer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateField(auto_now_add=True, verbose_name="Data de Criação"),
                ),
                (
                    "modified",
                    models.DateField(
                        auto_now_add=True, verbose_name="Data de Atualização"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                ("name", models.CharField(max_length=100)),
                ("bio", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "key",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("C", "C"),
                            ("C#", "C#"),
                            ("Db", "Db"),
                            ("D", "D"),
                            ("D#", "D#"),
                            ("Eb", "Eb"),
                            ("E", "E"),
                            ("F", "F"),
                            ("F#", "F#"),
                            ("Gb", "Gb"),
                            ("G", "G"),
                            ("G#", "G#"),
                            ("Ab", "Ab"),
                            ("A", "A"),
                            ("A#", "A#"),
                            ("Bb", "Bb"),
                            ("B", "B"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("lyrics", models.TextField(blank=True, null=True)),
                ("duration", models.DurationField(blank=True, null=True)),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "artist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="songs",
                        to="worship.composer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SongTheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateField(auto_now_add=True, verbose_name="Data de Criação"),
                ),
                (
                    "modified",
                    models.DateField(
                        auto_now_add=True, verbose_name="Data de Atualização"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SongFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateField(auto_now_add=True, verbose_name="Data de Criação"),
                ),
                (
                    "modified",
                    models.DateField(
                        auto_now_add=True, verbose_name="Data de Atualização"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                ("file", models.FileField(upload_to="song_files/")),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("audio", "Áudio"),
                            ("sheet", "Partitura"),
                            ("other", "Outro"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="worship.song",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="song",
            name="themes",
            field=models.ManyToManyField(
                blank=True, related_name="songs", to="worship.songtheme"
            ),
        ),
    ]
