# Generated by Django 4.2.5 on 2024-10-26 18:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("worship", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="duration",
        ),
    ]
