# Generated by Django 4.2.5 on 2024-10-29 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("worship", "0002_remove_song_duration"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hymnal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, unique=True)),
                ("author", models.CharField(blank=True, max_length=100, null=True)),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("edition", models.IntegerField(unique=True)),
                (
                    "theme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="worship.songtheme",
                    ),
                ),
            ],
        ),
    ]
