# Generated by Django 4.2.5 on 2024-10-29 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("worship", "0003_hymnal"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="hymnal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hymnal_songs",
                to="worship.hymnal",
            ),
        ),
    ]
