# Generated by Django 4.2.5 on 2024-10-29 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("worship", "0004_song_hymnal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hymnal",
            name="edition",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
