# Generated by Django 4.2.5 on 2024-12-21 23:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("worship", "0005_alter_hymnal_edition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="lyrics",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
