# Generated by Django 4.2.5 on 2025-01-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("worship", "0006_alter_song_lyrics"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="syllable_counts_json",
            field=models.JSONField(default=dict),
        ),
    ]
