# Generated by Django 4.2.5 on 2025-02-02 18:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("worship", "0008_song_metrics"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="syllable_counts_json",
        ),
    ]
