# Generated by Django 4.2.5 on 2025-02-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("worship", "0009_remove_song_syllable_counts_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="songfile",
            name="file_title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
