# Generated by Django 5.2.4 on 2026-02-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worship', '0012_worshipservice_program_font_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='worshipservice',
            name='leader_dirigente',
            field=models.CharField(blank=True, max_length=100, verbose_name='Dirigente'),
        ),
        migrations.AddField(
            model_name='worshipservice',
            name='leader_musician',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pianista/Músico'),
        ),
        migrations.AddField(
            model_name='worshipservice',
            name='leader_regente',
            field=models.CharField(blank=True, max_length=100, verbose_name='Regente'),
        ),
        migrations.AlterField(
            model_name='worshipservice',
            name='leaders_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Liderança'),
        ),
        migrations.AlterField(
            model_name='worshipservice',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='worshipservice',
            name='program_font_scale',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Escala da fonte'),
        ),
        migrations.AlterField(
            model_name='worshipservice',
            name='program_html',
            field=models.TextField(blank=True, verbose_name='Programação'),
        ),
        migrations.AlterField(
            model_name='worshipservice',
            name='service_date',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='worshipservice',
            name='service_kind',
            field=models.CharField(choices=[('REGULAR', 'Culto regular'), ('COMMUNION', 'Culto de ceia'), ('CANTATA', 'Cantata'), ('SPECIAL', 'Culto especial')], default='REGULAR', max_length=20, verbose_name='Tipo de culto'),
        ),
        migrations.AlterField(
            model_name='worshipservice',
            name='service_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário'),
        ),
        migrations.AlterField(
            model_name='worshipservice',
            name='title',
            field=models.CharField(max_length=180, verbose_name='Título'),
        ),
    ]
