from .custom_user_test_case import CustomUserTestCase
from .update_profile_view_tests import UserProfileUpdateViewTestAsSecretary
from .user_profile_view_test import UserProfileViewTest
from .registration_form_tests import RegisterUserFormTest
from .update_user_form_tests import UpdateUserProfileFormTest