# Generated by Django 5.2.4 on 2026-01-30 16:13

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuário que criou a transação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='reverses',
            field=models.ForeignKey(blank=True, help_text='Para estornos, aponta para a transação original', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_by', to='treasury.transactionmodel'),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='transaction_type',
            field=models.CharField(choices=[('original', 'Original'), ('reversal', 'Estorno')], default='original', help_text='Tipo da transação (original ou estorno)', max_length=20),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Primeiro dia do mês de referência', unique=True)),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('closed', 'Fechado'), ('archived', 'Arquivado')], default='open', help_text='Status atual do período', max_length=20)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Saldo inicial do período', max_digits=10)),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Saldo final fixado no fechamento', max_digits=10, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Observações sobre o fechamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, help_text='Usuário que fechou o período', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'período contábil',
                'verbose_name_plural': 'períodos contábeis',
                'ordering': ['-month'],
            },
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='accounting_period',
            field=models.ForeignKey(blank=True, help_text='Período contábil a que esta transação pertence', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='treasury.accountingperiod'),
        ),
        migrations.CreateModel(
            name='ReversalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Motivo do estorno')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authorized_by', models.ForeignKey(blank=True, help_text='Usuário que autorizou o estorno (para períodos arquivados)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_reversals', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='Usuário que criou o estorno', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reversals', to=settings.AUTH_USER_MODEL)),
                ('original_transaction', models.ForeignKey(help_text='Transação original que está sendo estornada', on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='treasury.transactionmodel')),
                ('reversal_transaction', models.ForeignKey(help_text='Nova transação que substitui a original', on_delete=django.db.models.deletion.PROTECT, related_name='reversed_original', to='treasury.transactionmodel')),
            ],
            options={
                'verbose_name': 'estorno de transação',
                'verbose_name_plural': 'estornos de transações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='accountingperiod',
            index=models.Index(fields=['month'], name='treasury_ac_month_1ad8bd_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingperiod',
            index=models.Index(fields=['status'], name='treasury_ac_status_896030_idx'),
        ),
        migrations.AddIndex(
            model_name='reversaltransaction',
            index=models.Index(fields=['original_transaction'], name='treasury_re_origina_c018b3_idx'),
        ),
        migrations.AddIndex(
            model_name='reversaltransaction',
            index=models.Index(fields=['reversal_transaction'], name='treasury_re_reversa_138c02_idx'),
        ),
        migrations.AddIndex(
            model_name='reversaltransaction',
            index=models.Index(fields=['created_at'], name='treasury_re_created_9e107b_idx'),
        ),
    ]
