# Generated by Django 5.2.4 on 2026-02-01 00:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0002_transactionmodel_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('period_id', models.UUIDField(help_text='ID do AccountingPeriod (referência sem FK)')),
                ('period_month', models.IntegerField(help_text='Mês do período (1-12)')),
                ('period_year', models.IntegerField(help_text='Ano do período')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_id', models.IntegerField(help_text='ID do usuário que criou o snapshot', null=True)),
                ('created_by_name', models.CharField(blank=True, help_text='Nome do usuário que criou', max_length=255)),
                ('reason', models.TextField(help_text="Motivo da criação do snapshot (ex: 'Reabertura para estorno da transação #123')")),
                ('snapshot_data', models.JSONField(help_text='Dados completos do período no momento do snapshot')),
                ('transactions_count', models.IntegerField(default=0)),
                ('closing_balance', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('was_closed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Snapshot de Período',
                'verbose_name_plural': 'Snapshots de Períodos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['period_id', '-created_at'], name='treasury_pe_period__4080e5_idx'), models.Index(fields=['created_by_id'], name='treasury_pe_created_8c2654_idx'), models.Index(fields=['period_month', 'period_year'], name='treasury_pe_period__1fda6e_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('period_opened', 'Período Aberto'), ('period_closed', 'Período Fechado'), ('period_reopened', 'Período Reaberto'), ('period_archived', 'Período Arquivado'), ('period_recalculated', 'Período Recalculado'), ('transaction_created', 'Transação Criada'), ('transaction_updated', 'Transação Atualizada'), ('transaction_deleted', 'Transação Deletada'), ('transaction_reversed', 'Transação Estornada'), ('snapshot_created', 'Snapshot Criado'), ('snapshot_restored', 'Snapshot Restaurado'), ('report_generated', 'Relatório Gerado'), ('report_regenerated', 'Relatório Regenerado')], db_index=True, help_text='Ação realizada', max_length=50)),
                ('entity_type', models.CharField(choices=[('AccountingPeriod', 'Período Contábil'), ('TransactionModel', 'Transação'), ('PeriodSnapshot', 'Snapshot de Período'), ('MonthlyReportModel', 'Relatório Mensal'), ('CategoryModel', 'Categoria')], db_index=True, help_text='Tipo de entidade afetada', max_length=50)),
                ('entity_id', models.IntegerField(db_index=True, help_text='ID da entidade afetada (sem FK por ser cross-db)')),
                ('old_values', models.JSONField(blank=True, help_text='Valores antes da alteração', null=True)),
                ('new_values', models.JSONField(blank=True, help_text='Valores após a alteração', null=True)),
                ('description', models.TextField(blank=True, help_text='Descrição opcional da alteração')),
                ('snapshot_id', models.UUIDField(blank=True, db_index=True, help_text='UUID do snapshot relacionado (se houver)', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP de onde veio a requisição', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent do navegador')),
                ('period_id', models.IntegerField(blank=True, db_index=True, help_text='ID do período contábil relacionado (para filtros rápidos)', null=True)),
                ('user', models.ForeignKey(blank=True, help_text='Usuário que fez a alteração', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='audit_log_timesta_8b04a8_idx'), models.Index(fields=['action'], name='audit_log_action_b32d4d_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_log_entity__c2633a_idx'), models.Index(fields=['user', '-timestamp'], name='audit_log_user_id_79f582_idx'), models.Index(fields=['period_id'], name='audit_log_period__e627c7_idx')],
            },
        ),
    ]
