# Generated by Django 5.2.4 on 2026-02-01 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0003_periodsnapshot_auditlog'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_log_user_id_79f582_idx',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='user',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_id',
            field=models.IntegerField(blank=True, help_text='ID do usuário que fez a alteração', null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_name',
            field=models.CharField(blank=True, help_text='Nome do usuário que fez a alteração', max_length=255),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user_id', '-timestamp'], name='audit_log_user_id_79f582_idx'),
        ),
    ]
