# Generated by Django 5.2.4 on 2026-02-01 16:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0004_remove_auditlog_audit_log_user_id_79f582_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FrozenReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('analytical', 'Relatório Analítico'), ('extract', 'Extrato de Transações')], default='analytical', max_length=20)),
                ('pdf_file', models.FileField(upload_to='frozen_reports/%Y/%m/')),
                ('pdf_hash', models.CharField(help_text='SHA256 do PDF (hex)', max_length=64)),
                ('closing_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_positive', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_negative', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_recovered', models.BooleanField(default=False, help_text='True se foi recuperado de uma verificação que falhou')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frozen_reports', to='treasury.accountingperiod')),
                ('replaces_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='treasury.frozenreport')),
            ],
            options={
                'verbose_name': 'Relatório Congelado',
                'verbose_name_plural': 'Relatórios Congelados',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['period', '-created_at'], name='treasury_fr_period__2651e5_idx'), models.Index(fields=['report_type', '-created_at'], name='treasury_fr_report__7d09cf_idx'), models.Index(fields=['pdf_hash'], name='treasury_fr_pdf_has_e224cd_idx')],
            },
        ),
    ]
