# Generated by Django 5.2.4 on 2026-02-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0005_frozenreport'),
    ]

    operations = [
        # Primeiro, corrigir valores NULL em notes para evitar erro na migração do SQLite
        migrations.RunSQL(
            "UPDATE treasury_accountingperiod SET notes = '' WHERE notes IS NULL",
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.AddField(
            model_name='accountingperiod',
            name='is_first_month',
            field=models.BooleanField(default=False, help_text='Marca se este é o período inicial com saldo de importação'),
        ),
    ]
