# Generated by Django 5.2.4 on 2026-02-01 19:02

from django.db import migrations, models


def fix_notes(apps, schema_editor):
    # Só executa no banco default, não no audit
    if schema_editor.connection.alias != 'default':
        return
    AccountingPeriod = apps.get_model('treasury', 'AccountingPeriod')
    for period in AccountingPeriod.objects.filter(notes__isnull=True):
        period.notes = ''
        period.save(update_fields=['notes'])


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0005_frozenreport'),
    ]

    operations = [
        # Primeiro, corrigir valores NULL em notes para evitar erro na migração do SQLite
        migrations.RunPython(fix_notes, migrations.RunPython.noop),
        migrations.AddField(
            model_name='accountingperiod',
            name='is_first_month',
            field=models.BooleanField(default=False, help_text='Marca se este é o período inicial com saldo de importação'),
        ),
    ]
