# Generated by Django 5.2.4 on 2026-02-02 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0006_accountingperiod_is_first_month'),
    ]

    operations = [
    ]
