# Generated by Django 5.2.4 on 2026-02-02 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0007_auto_20260202_1413'),
    ]

    operations = [
    ]
