# Generated by Django 5.2.4 on 2026-02-02 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0009_auto_20260202_1426'),
    ]

    operations = [
        # Marcar MonthlyBalance como managed=False para não gerenciá-lo nas migrations
        # A tabela continua existindo no banco, mas o Django não tentará criá-la/removê-la
        migrations.AlterModelOptions(
            name='monthlybalance',
            options={'managed': False, 'verbose_name': 'Saldo Mensal', 'verbose_name_plural': 'Saldos Mensais'},
        ),
    ]
