# Generated by Django 5.2.4 on 2026-02-02 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0010_auto_20260202_2027'),
    ]

    operations = [
        # Usamos SeparateDatabaseAndState para evitar problemas com SQLite
        # O estado do Django é atualizado (código usa FileField)
        # Mas o banco não é modificado (continua como estava)
        # Isso funciona porque FileField e ResizedImageField são compatíveis no nível de banco
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='transactionmodel',
                    name='acquittance_doc',
                    field=models.FileField(blank=True, null=True, upload_to='treasury.utils.custom_upload_to.custom_upload_to'),
                ),
            ],
            database_operations=[
                # Nenhuma operação no banco - mantemos o campo como está
            ],
        ),
    ]
