# Generated by Django 5.2.4 on 2026-02-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0011_alter_transactionmodel_acquittance_doc'),
    ]

    operations = [
        # Usamos SeparateDatabaseAndState para evitar problemas com SQLite
        # Atualiza o estado do Django para refletir o upload_to correto
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='transactionmodel',
                    name='acquittance_doc',
                    field=models.FileField(blank=True, null=True, upload_to='treasury.custom_upload_to'),
                ),
            ],
            database_operations=[
                # Nenhuma operação no banco
            ],
        ),
    ]
