# Generated by Django 5.2.4 on 2026-02-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0013_alter_transactionmodel_acquittance_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('content', models.TextField(help_text='Conteúdo markdown dos insights gerados')),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('transactions_count', models.PositiveIntegerField(help_text='Número de transações usadas para gerar o insight. Se mudar, o cache é invalidado.')),
                ('model_used', models.CharField(help_text='Modelo de IA usado (ex: ollama/ministral-3:8b, mistral-small-latest)', max_length=50)),
                ('debug_mode', models.BooleanField(default=True, help_text='Se estava em DEBUG mode (Ollama) ou produção (Mistral API)')),
            ],
            options={
                'verbose_name': 'Insight de IA',
                'verbose_name_plural': 'Insights de IA',
                'db_table': 'treasury_ai_insights',
                'ordering': ['-generated_at'],
                'constraints': [models.UniqueConstraint(fields=('start_date', 'end_date'), name='unique_ai_insight_period')],
            },
        ),
    ]
