# Generated by Django 5.2.4 on 2026-02-03 18:34
"""
Data migration para converter o schema antigo (treasury_monthlybalance)
para o novo schema (treasury_accountingperiod).

Esta migration é IDEMPOTENTE - pode ser rodada múltiplas vezes sem problemas.
Ela detecta automaticamente se o schema antigo existe e faz a conversão.
"""

from django.db import migrations, connection


def forward_migration(apps, schema_editor):
    """
    Migra dados do schema antigo para o novo.

    Schema antigo:
    - treasury_monthlybalance (id, month, balance, created, modified)

    Schema novo:
    - treasury_accountingperiod (id, month, status, opening_balance, closing_balance, ...)
    - treasury_transactionmodel com colunas adicionais
    """
    cursor = connection.cursor()

    # 1. Verificar se a tabela antiga existe
    cursor.execute("""
        SELECT name FROM sqlite_master
        WHERE type='table' AND name='treasury_monthlybalance';
    """)
    old_table_exists = cursor.fetchone() is not None

    if not old_table_exists:
        # Tabela antiga não existe - schema já é novo, nada a fazer
        return

    # 2. Verificar se a tabela nova já existe
    cursor.execute("""
        SELECT name FROM sqlite_master
        WHERE type='table' AND name='treasury_accountingperiod';
    """)
    new_table_exists = cursor.fetchone() is not None

    if new_table_exists:
        # Tabela nova já existe, apenas migrar dados
        print("Migrando dados de monthlybalance para accountingperiod...")
        cursor.execute("""
            INSERT OR IGNORE INTO treasury_accountingperiod
                (id, month, status, opening_balance, closing_balance, created_at, updated_at)
            SELECT
                id,
                month,
                CASE WHEN balance > 0 THEN 'closed' ELSE 'open' END as status,
                0.0 as opening_balance,
                balance as closing_balance,
                created as created_at,
                modified as updated_at
            FROM treasury_monthlybalance;
        """)
    else:
        # Criar tabela nova e migrar dados
        print("Criando tabela treasury_accountingperiod e migrando dados...")
        cursor.execute("""
            CREATE TABLE treasury_accountingperiod (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                month DATE NOT NULL UNIQUE,
                status VARCHAR(20) NOT NULL DEFAULT 'open',
                opening_balance DECIMAL(10,2) NOT NULL DEFAULT 0.0,
                closing_balance DECIMAL(10,2) NULL,
                closed_at TIMESTAMP NULL,
                closed_by_id INTEGER NULL,
                notes TEXT NULL,
                created_at TIMESTAMP NULL,
                updated_at TIMESTAMP NULL,
                is_first_month BOOLEAN DEFAULT 0,
                FOREIGN KEY (closed_by_id) REFERENCES users_customuser(id)
            );
        """)

        # Migrar dados
        cursor.execute("""
            INSERT INTO treasury_accountingperiod
                (id, month, status, opening_balance, closing_balance, created_at, updated_at)
            SELECT
                id,
                month,
                CASE WHEN balance > 0 THEN 'closed' ELSE 'open' END as status,
                0.0 as opening_balance,
                balance as closing_balance,
                created as created_at,
                modified as updated_at
            FROM treasury_monthlybalance;
        """)

    # 3. Adicionar colunas na transactionmodel se não existirem
    # SQLite não suporta ADD COLUMN IF NOT EXISTS, então verificamos manualmente

    # Verificar colunas existentes
    cursor.execute("PRAGMA table_info(treasury_transactionmodel)")
    existing_columns = {row[1] for row in cursor.fetchall()}

    # Adicionar colunas faltantes
    columns_to_add = {
        'transaction_type': "VARCHAR(20) DEFAULT 'original'",
        'created_at': 'TIMESTAMP',
        'updated_at': 'TIMESTAMP',
        'accounting_period_id': 'INTEGER NULL',
        'reverses_id': 'INTEGER NULL',
        'created_by_id': 'INTEGER NULL',
    }

    for column, definition in columns_to_add.items():
        if column not in existing_columns:
            print(f"Adicionando coluna {column}...")
            cursor.execute(f"""
                ALTER TABLE treasury_transactionmodel
                ADD COLUMN {column} {definition};
            """)

    # 4. Vincular transações aos períodos
    print("Vinculando transações aos períodos...")
    cursor.execute("""
        UPDATE treasury_transactionmodel
        SET accounting_period_id = (
            SELECT id FROM treasury_accountingperiod
            WHERE strftime('%Y-%m', treasury_transactionmodel.date) = strftime('%Y-%m', month)
            LIMIT 1
        )
        WHERE accounting_period_id IS NULL;
    """)

    # 5. Preencher created_by_id
    print("Preenchendo created_by_id...")
    cursor.execute("""
        UPDATE treasury_transactionmodel
        SET created_by_id = user_id
        WHERE created_by_id IS NULL;
    """)


def reverse_migration(apps, schema_editor):
    """
    Reverse não é necessário - não vamos desfazer a migração.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0014_ai_insight_model'),
    ]

    operations = [
        migrations.RunPython(forward_migration, reverse_migration),
    ]
