# Generated by Django 5.2.4 on 2026-02-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0014_ai_insight_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='minute_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='ID da ata relacionada (para filtros rápidos)', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('period_opened', 'Período Aberto'), ('period_closed', 'Período Fechado'), ('period_reopened', 'Período Reaberto'), ('period_archived', 'Período Arquivado'), ('period_recalculated', 'Período Recalculado'), ('transaction_created', 'Transação Criada'), ('transaction_updated', 'Transação Atualizada'), ('transaction_deleted', 'Transação Deletada'), ('transaction_reversed', 'Transação Estornada'), ('snapshot_created', 'Snapshot Criado'), ('snapshot_restored', 'Snapshot Restaurado'), ('report_generated', 'Relatório Gerado'), ('report_regenerated', 'Relatório Regenerado'), ('minute_created', 'Ata Criada'), ('minute_updated', 'Ata Atualizada'), ('minute_deleted', 'Ata Deletada'), ('minute_signed', 'Ata Assinada'), ('minute_pdf_generated', 'PDF de Ata Gerado'), ('excerpt_created', 'Excerto Criado'), ('excerpt_updated', 'Excerto Atualizado'), ('excerpt_deleted', 'Excerto Deletado'), ('template_created', 'Template Criado'), ('template_updated', 'Template Atualizado'), ('template_deleted', 'Template Deletado'), ('project_created', 'Projeto Criado'), ('project_updated', 'Projeto Atualizado'), ('project_deleted', 'Projeto Deletado'), ('file_uploaded', 'Arquivo Enviado'), ('file_deleted', 'Arquivo Deletado'), ('agenda_created', 'Agenda Criada'), ('agenda_updated', 'Agenda Atualizada'), ('agenda_deleted', 'Agenda Deletada')], db_index=True, help_text='Ação realizada', max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_type',
            field=models.CharField(choices=[('AccountingPeriod', 'Período Contábil'), ('TransactionModel', 'Transação'), ('PeriodSnapshot', 'Snapshot de Período'), ('MonthlyReportModel', 'Relatório Mensal'), ('CategoryModel', 'Categoria'), ('MeetingMinuteModel', 'Ata'), ('MinuteExcerptsModel', 'Excerto'), ('MinuteTemplateModel', 'Template'), ('MinuteProjectModel', 'Projeto'), ('MinuteFileModel', 'Arquivo'), ('MeetingAgendaModel', 'Agenda')], db_index=True, help_text='Tipo de entidade afetada', max_length=50),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['minute_id'], name='audit_log_minute__521c7f_idx'),
        ),
    ]
