# Generated by Django 5.2.4 on 2026-04-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0019_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingperiod',
            name='balance_adjustment_reason',
            field=models.TextField(blank=True, default='', help_text='Motivo do ajuste manual do saldo'),
        ),
    ]
