from .register_form_view import RegisterFormView
from .signup_form_view import SignupFormView
from .user_profile_view import UserProfileView
from .update_user_profile_view import UserProfileUpdateView
from .change_user_password_view import ChangeUserPasswordView
from .user_update_type import UpdateUserTypeView
from .user_update_functions import UpdateUserFunctionView
